# name: applications-android-classical
# content: Android 常用应用直连规则
# update_date: 20251130
# update_url: https://raw.githubusercontent.com/nekohalawrence/PCR/main/rule/mihomo/applications-android-classical.yaml
# repo: https://github.com/nekohalawrence/PCR/tree/main/rule/mihomo

# DOMAIN
# DOMAIN-SUFFIX
# DOMAIN-KEYWORD
# IP-CIDR

payload:
  - PROCESS-NAME,com.eg.android.AlipayGphone
  - PROCESS-NAME,com.ss.android.ugc.aweme
  - PROCESS-NAME,com.tencent.mm